[workspace]
members = [
  "contracts/manager",
  "contracts/transceiver",
  "contracts/soroban-ntt-client",
]

resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
soroban-sdk = { version = "25.1.1", features = ["hazmat-address"] }
stellar-xdr = "25"
wormhole-soroban-client = { git = "https://github.com/NethermindEth/wormhole", branch = "stellar" }
soroban-ntt-client = { path = "contracts/soroban-ntt-client" }

[profile.release]
overflow-checks = true
