[package]
name = "stellar-ntt-manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]
name = "stellar_ntt_manager"

[dependencies]
soroban-sdk = { workspace = true, features = ["alloc"] }
wormhole-soroban-client = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }