[package]
name = "stellar-ntt-manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "stellar_ntt_manager"

[dependencies]
soroban-sdk = { workspace = true }
wormhole-soroban-client = { workspace = true }
soroban-ntt-client = { workspace = true }
stellar-access = { workspace = true }
stellar-contract-utils = { workspace = true }
stellar-macros = { workspace = true }
