[package]
name = "stellar-ntt-transceiver"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "stellar_ntt_transceiver"

[dependencies]
soroban-sdk = { workspace = true }
wormhole-soroban-client = { workspace = true }
soroban-ntt-client = { workspace = true }
stellar-access = { workspace = true }
stellar-contract-utils = { workspace = true }
stellar-macros = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
soroban-ntt-client = { workspace = true }
wormhole-soroban-client = { workspace = true }
wormhole-contract = { git = "https://github.com/NethermindEth/wormhole", branch = "stellar" }
vaa-test-signing = { workspace = true }
